"""Configuration package for MOEPP air quality pipeline."""

from .constants import (
    ALLOWED_AGGREGATIONS,
    ALLOWED_PARAMETERS,
    DATE_FORMAT,
    DEFAULT_AGGREGATION,
    MAX_DATE_RANGE_DAYS,
    MIN_DATE,
)
from .logger import configure_logging, get_logger
from .mappings import (
    ALL_REGION_IDS,
    ALL_STATION_IDS,
    REGION_STATIONS,
    STATION_NAMES,
)
from .settings import (
    BASE_URL,
    DEFAULT_DUCKLAKE_METADATA_PATH,
    DEFAULT_LOG_LEVEL,
    DEFAULT_OUTPUT_DB,
    DEFAULT_PRIMARY_KEY,
    DEFAULT_REQUEST_DELAY,
    DEFAULT_TABLE_NAME,
    DEFAULT_TIMEOUT,
    DUCKLAKE_CATALOG_NAME,
    DUCKLAKE_CATALOG_R2_KEY,
    DUCKLAKE_DATA_R2_PREFIX,
    MAX_RETRIES,
    RETRY_BACKOFF_FACTOR,
    catalog_public_url,
    get_log_level,
    get_output_db,
    get_r2_public_base_url,
    require_r2_writer_config,
)

__all__ = [
    'ALLOWED_AGGREGATIONS',
    'ALLOWED_PARAMETERS',
    'ALL_REGION_IDS',
    'ALL_STATION_IDS',
    'BASE_URL',
    'DATE_FORMAT',
    'DEFAULT_AGGREGATION',
    'DEFAULT_DUCKLAKE_METADATA_PATH',
    'DEFAULT_LOG_LEVEL',
    'DEFAULT_OUTPUT_DB',
    'DEFAULT_PRIMARY_KEY',
    'DEFAULT_REQUEST_DELAY',
    'DEFAULT_TABLE_NAME',
    'DEFAULT_TIMEOUT',
    'DUCKLAKE_CATALOG_NAME',
    'DUCKLAKE_CATALOG_R2_KEY',
    'DUCKLAKE_DATA_R2_PREFIX',
    'MAX_DATE_RANGE_DAYS',
    'MAX_RETRIES',
    'MIN_DATE',
    'REGION_STATIONS',
    'RETRY_BACKOFF_FACTOR',
    'STATION_NAMES',
    'catalog_public_url',
    'configure_logging',
    'get_log_level',
    'get_logger',
    'get_output_db',
    'get_r2_public_base_url',
    'require_r2_writer_config',
]
